'use client'
import type {Metadata} from 'next'
import SideBar from "@/components/SideBar/SideBar";
import Header from "@/components/Header/Header";
import '../styles/globals.scss'
import {Providers} from "@/components/Providers/Providers";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Providers>
            <Header/>
            <SideBar>
                <div style={{padding: 20}}>
                    {children}
                </div>
            </SideBar>
        </Providers>
        </body>
        </html>
    )
}
